### ISSUE TITLE
ci: integrate GitHub Actions for branch testing

### ISSUE THREAD

**Issue by szeller** [szeller/whatsontv#10]
Set up GitHub Actions workflow to automatically test all branches

## Objectives
- Implement CI/CD pipeline using GitHub Actions
- Test all branches automatically
- Enforce code quality standards
- Generate and store test coverage reports

## Tasks
- [ ] Create GitHub Actions workflow:
  ```yaml
  name: Test
  on:
    push:
      branches: ['*']
    pull_request:
      branches: [main]

  jobs:
    test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: '18'
            cache: 'npm'
        - run: npm ci
        - run: npm test
  ```
- [ ] Add coverage reporting:
  - Configure Jest coverage output
  - Store coverage artifacts
  - Add coverage badges
- [ ] Configure linting checks:
  - ESLint with TypeScript
  - Prettier formatting
  - No warnings policy
- [ ] Set up branch protections:
  - Require passing tests
  - Enforce coverage thresholds
  - Require code review

## Implementation Details
- Use TypeScript version constraints (>=4.7.4 <5.6.0)
- Configure Jest v29.x.x
- Set up ESLint v8.x.x
- Add test coverage thresholds:
  - Statements: 80%
  - Branches: 80%
  - Functions: 80%
  - Lines: 80%

## Requirements
- Follow established code style
- Document CI/CD process
- Add status badges to README
- Configure notifications
- Store test artifacts
- Add deployment stages
